# Generated by Django 4.1.2 on 2023-04-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUsers',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('EmailID', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.IntegerField(unique=True)),
                ('Password', models.CharField(max_length=25)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('City', models.CharField(blank=True, max_length=25, null=True)),
                ('State', models.CharField(blank=True, max_length=25, null=True)),
                ('Zip', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('UserStatus', models.BooleanField(default=True)),
            ],
        ),
    ]
