# Generated by Django 4.1.2 on 2023-04-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerusers',
            name='EmailID',
            field=models.EmailField(max_length=254),
        ),
    ]
