# Generated by Django 4.1.2 on 2023-04-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textiles', '0002_alter_registerusers_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerusers',
            name='Phone',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
