# Generated by Django 4.1.2 on 2023-04-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textiles', '0003_alter_registerusers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerusers',
            name='Phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
