# Generated by Django 4.1.2 on 2023-05-03 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textiles', '0007_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='UserID',
        ),
        migrations.AlterField(
            model_name='orders',
            name='ContactNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 1, 3, 32, 815204)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='No_Of_Items',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='OrderStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('production', 'Production'), ('complated', 'complited')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='WhatsappNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
