# Generated by Django 4.1.2 on 2023-05-04 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textiles', '0009_delete_registerusers_orders_user_alter_orders_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUsers',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('EmailID', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField(max_length=10)),
                ('Password', models.CharField(max_length=25)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('City', models.CharField(blank=True, max_length=25, null=True)),
                ('State', models.CharField(blank=True, max_length=25, null=True)),
                ('Zip', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('UserStatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 23, 7, 53, 984159)),
        ),
    ]
