# Generated by Django 4.1.2 on 2023-05-05 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textiles', '0010_registerusers_alter_orders_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='TransactionId',
            field=models.CharField(blank=True, default=0, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 1, 19, 46, 760246)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='OrderStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Production', 'Production'), ('Delivery', 'Delivery'), ('completed', 'completed')], default='pending', max_length=20),
        ),
    ]
