# Generated by Django 4.1.2 on 2023-05-05 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textiles', '0011_orders_transactionid_alter_orders_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 2, 31, 50, 944544)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
